Add hetrogenous network for azure and aws.
redhat-performance/zathras pull request #10
Opened 2023-01-16 10:07 UTC by dvalinrh

2023-01-24 11:14 UTC, sousinha97 approved these changes

2023-02-02 17:47 UTC, frival commented on ansible_roles/roles/azure_create/tasks/main.yml
> +    line: "instance start_time: {{ (azure_create_time_start.stdout) | int - (azure_create_time_start.stdout) | int }}"
That can't be right...

2023-02-02 17:51 UTC, frival commented on bin/burden
> +	echo here we are
Debug cruft

2023-02-02 17:59 UTC, frival requested changes
Also assuming this has been tested with no network, heterogeneous network, and homogeneous network.  But you know what happens when you assume...

2023-02-02 17:59 UTC, frival commented on bin/burden
> +		echo here we are1
Also debug cruft

2023-02-02 17:59 UTC, frival commented on bin/burden
> +	echo here we are
Debug cruft

2023-02-02 17:59 UTC, frival commented on bin/burden
> +		echo "             the name of the system working with.  In the case of the cloud, if the second system"
I think this line needs to start with "be"

2023-02-02 17:59 UTC, frival commented on bin/burden
>  	fi
Please add an example for the heterogeneous networks case.

2023-02-03 09:39 UTC, closed without merging