Add Image/Package Mode feature to `os_vendor`
redhat-performance/zathras pull request #102
Opened 2024-08-29 16:16 UTC by kdvalin

This PR adds the ability to simply specify `os_vendor: rhel:mode=image` to work with bootc images.

Presently all this does is enable `--no_packages` automatically since you cannot install packages in bootc/image mode.

2024-08-29 21:04 UTC, kdvalin commented
Trying a smoke test using a FIO bootc image, currently hitting this
```
TASK [existing_uploads_dir : Make the uploads directory] ***********************
fatal: [192.168.122.143]: FAILED! => {"changed": false, "msg": "There was an issue creating /sysroot/uploads as requested: [Errno 30] Read-only file system: b'/sysroot/uploads'", "path": "/sysroot/uploads"}
```

This'll be fun

2024-08-29 21:09 UTC, kdvalin commented
Updating the `kit_upload_directory` to be within `/root` fixed that problem, will fix it tomorrow.

2024-09-12 09:41 UTC, dvalinrh commented on bin/burden
> +		echo $os_args
Debug? if so please remove

2024-09-12 09:42 UTC, dvalinrh commented on bin/burden
> +	arg_file=$(mktemp)
So if we see the tmp file for some reason we know what it is.
mktemp /tmp/zath_prcs_os_args.XXXXX

2024-09-12 09:44 UTC, dvalinrh commented on bin/utils/parse_optstring.sh
> +        echo "${key_name}:"
Debug?

2024-10-29 09:58 UTC, dvalinrh submitted a review, later dismissed
LGTM

2025-01-07 13:47 UTC, kdvalin commented on bin/burden
> +				gl_kit_upload_directory="/root"
`/root` issues with public cloud.

2025-01-07 13:47 UTC, kdvalin commented on bin/burden
> +				gl_kit_upload_directory="/root"
Maybe SSH into host to figure out user directory

2025-01-21 13:38 UTC, dvalinrh requested changes
Work in project.

2025-02-10 19:24 UTC, kdvalin commented
This will be moved into a new PR since this was based off a fork, which none of the workflows work with.  Yay!

2025-02-10 19:24 UTC, closed without merging