burden break up, large scenario lines
redhat-performance/zathras pull request #104
Opened 2024-09-03 11:08 UTC by dvalinrh

Move the code that is used to breakup large lines in the scenario file into a utility script.

2024-09-03 17:55 UTC, kdvalin requested changes
The idea behind breaking up `burden` is not just to break it out to multiple files, but to break it out to multiple files, and each file does a specific thing that the name of the file describes.

For example: one file could be for validating the scenario file and handling error conditions specifically with the scenario file, named `validate_scenario`.

Some things like `exit_out` could be stuck in a common file which we can `source`, that way we can reuse it no matter what script we're using.

2024-09-04 10:28 UTC, dvalinrh commented
Changed new file name to something more meaningful.

2024-09-04 13:36 UTC, kdvalin approved these changes
LGTM, left a comment for future break-apart work.

2024-09-04 13:36 UTC, kdvalin commented on bin/utils/brk_up_large_scn_host_configs
> +
This is fine for now, but `exit_out` will probably be used across many files, so it should be in a library shell file _somewhere_ that the scripts will `source` from.

2024-09-04 13:49 UTC, merged