Documentation rewrite - phase one
redhat-performance/zathras pull request #112
Opened 2024-09-10 17:40 UTC by grdumas

Documentation in Zathras is currently spread across multiple files, which can create confusion about where to go for information. In order to reduce this confusion, and to improve the readability and maintainability of our documentation, this PR implements the first phase of a larger docs rewrite for Zathras.

The goal of this phase is to revamp the documentation on a structural level (described more below), which will be followed by further expanding and updating the documentation's contents. In order to not lose the knowledge captured by existing documentation, older docs have been moved to a subdirectory within docs/ until the new documentation can fully stand on its own.

Summary of major changes:
- Primary repo README is now geared towards new Zathras users by providing an overview of the project and linking to separate quickstart resources for installation and testing.
- Key Zathras subcomponents and concepts (scenario files, test config files, running tests) now have their own pages. Separating documentation like this serves two purposes: 1) it keeps each doc short and avoids overwhelming users via info dumps, and 2) it improves the maintainability of the documentation by only requiring information to be updated in one place.

2024-09-11 09:09 UTC, dvalinrh commented on README.md
> +Currently, Zathras offers the following test wrappers:
Change currently to be 
As of 09/11/204
That way there is a time date present, and if a test is added it does not automatically cause problems.
Also add a line something like this.
To see the current available tests the version you are running, and the latest version issue the following command
./burden --test_version_check

2024-09-11 09:11 UTC, dvalinrh commented on README.md
> +5. Once results have been retrieved, Zathras will attempt to cleanup the testing environment (such as by tearing down instances in the cloud or by removing directories and files on bare metal).
Add this info
To not have zathras cleanup, use the option  --no_clean_up to the command line.

2024-09-11 09:12 UTC, dvalinrh commented on README.md
> +2. One or more systems where tests will be run. This can be another physical system (aka bare metal), an instance on a public cloud like Amazon Web Services (AWS), or even a virtual machine (VM) eith
For cloud.  Instance is created for us.  If the cloud instance already exists we can treat it as a bare metal machine.

2024-09-11 09:13 UTC, dvalinrh commented on README.md
> +Test config files, stored in the config/ directory of the Zathras installation, are the connective tissue between Zathras and the test wrappers. Currently this Zathras repo does not contain any defin
Typo, tissue

2024-09-11 09:15 UTC, dvalinrh commented on README.md
> +- [Testing on bare metal](https://github.com/redhat-performance/zathras/blob/documentation-rewrite/docs/test_config_files.md)
When you submit, make sure the changes goes to documentation, not documentation-rewrite and you update everything accordingly.

2024-09-11 09:18 UTC, dvalinrh requested changes
Looks good for the most part.  We need more then one person reviewing this though.

2024-09-16 19:00 UTC, kdvalin requested changes

2024-09-16 19:00 UTC, kdvalin commented on README.md
> +5. Once results have been retrieved, Zathras will attempt to cleanup the testing environment (such as by tearing down instances in the cloud or by removing directories and files on bare metal).
Maybe instead just "This step can be skipped using the `--no_clean_up` option"

2024-09-16 19:00 UTC, kdvalin commented on README.md
> +Test config files, stored in the config/ directory of the Zathras installation, are the connective tissue between Zathras and the test wrappers. Currently this Zathras repo does not contain any defin
This has also changed, config files are provided.

2024-09-16 19:00 UTC, kdvalin commented on docs/command_line_reference.md
> +Currently rhel, ubuntu, amazon.
This is not a Cloud-only option

2024-09-16 19:00 UTC, kdvalin commented on docs/scenario_files.md
> +This scenario would run the STREAM benchmark on a local bare metal system named "test_sys".
Probably best to mention the need for a `local_config` here, with a link to relevant documentation if available.

2025-10-08 19:08 UTC, malucius-rh commented on docs/test_config_files.md
> +test<n>: is a unique numerical value from the other tests. Other than for creation of the yml file, it has no bearing on the test execution.
"test should be boldface"

2025-10-08 19:08 UTC, malucius-rh commented on docs/test_config_files.md
> +**pbench_required**: If set to yes, the test requires pbench to be installed to run. Zathras will install pbench on the test system for you. Only supported for RHEL/Fedora. Note: it is the responsibi
pbench is no longer supported

2025-10-08 19:09 UTC, malucius-rh commented on docs/test_config_files.md
> +**rhel_pkgs**: RHEL packages that are required to run the test; “none” if there aren’t any packaging requirements
Are these going away with the package management changes?

2025-10-14 01:36 UTC, grdumas commented on docs/test_config_files.md
> +**pbench_required**: If set to yes, the test requires pbench to be installed to run. Zathras will install pbench on the test system for you. Only supported for RHEL/Fedora. Note: it is the responsibi
Fixed, thank you for the catch.

2025-10-14 01:45 UTC, grdumas commented on docs/test_config_files.md
> +test<n>: is a unique numerical value from the other tests. Other than for creation of the yml file, it has no bearing on the test execution.
Fixed.

2025-10-14 12:45 UTC, kdvalin commented on docs/test_config_files.md
> +**rhel_pkgs**: RHEL packages that are required to run the test; “none” if there aren’t any packaging requirements
They will, but since they are still valid options I don't think this should hold up the PR

2025-10-14 12:50 UTC, kdvalin approved these changes
LGTM

2025-10-20 13:31 UTC, dvalinrh approved these changes
LGTM

2025-10-20 13:37 UTC, merged