Handle spot termination when a test is running.
redhat-performance/zathras pull request #13
Opened 2023-01-19 13:05 UTC by dvalinrh

Two options
1) We will create the vm without spot pricing
2) We simply terminate.

2023-01-24 11:13 UTC, sousinha97 approved these changes

2023-02-09 14:56 UTC, frival commented on bin/kick_off.sh
> +					# Next attempt is with out spot pricing.
micro-nit: attempt *it*

2023-02-09 14:57 UTC, frival commented on bin/kick_off.sh
> +					grep -v "spot_range:" ansible_vars_main.yml | grep -v spot_range: > spot_repair
I'm curious why you're "grep -v"-ing twice here, the input through the pipe should be excluding spot_range: already.

2023-02-09 14:58 UTC, frival commented on bin/kick_off.sh
> +				echo Error: did not start the test.
We should log something to stable storage, this echo will get lost in the massive scrollback buffer any significant run creates.

2023-02-09 14:59 UTC, frival requested changes
Couple issues, both "relatively" minor.

2023-02-09 16:16 UTC, merged