Adding code to handle rerunning failed tests.
redhat-performance/zathras pull request #67
Opened 2024-02-26 13:58 UTC by dvalinrh

2024-03-06 16:40 UTC, kdvalin requested changes

2024-03-06 16:40 UTC, kdvalin commented on bin/burden
> +	sed_string="cat $scenario_cnvt_file"
Repeat of line 2551

2024-03-18 08:44 UTC, dvalinrh commented on bin/burden
> +	sed_string="cat $scenario_cnvt_file"
Good catch.  Fixed.

2024-03-18 13:24 UTC, kdvalin approved these changes
LGTM

2024-03-18 14:01 UTC, merged