Change double quotes to single quotes
redhat-performance/zathras pull request #78
Opened 2024-04-02 18:41 UTC by grdumas

The use of double quotes unintentionally led to Bash interpolating the contents of the string.

2024-04-03 08:35 UTC, dvalinrh commented
LGTM

2024-04-03 08:35 UTC, dvalinrh submitted a review, later dismissed

2024-12-20 23:24 UTC, grdumas commented
I need help fixing the merge conflicts.

2025-01-13 18:29 UTC, dvalinrh commented
Please update as talked about in code review meeting.

2025-01-14 13:12 UTC, grdumas commented
Before:
```
Before you can run Zathras:
****Ensure ~/.local/bin is in your path
./test_original.sh: line 6: syntax error near unexpected token `('
./test_original.sh: line 6: `echo '****If running a local system, create the local config file for the system under test (SUT)''
```

After:
```
Before you can run Zathras:
****Ensure ~/.local/bin is in your path
****Set up a scenario file
****If running a local system, create the local config file for the system under test (SUT)
****If using an existing system, ssh-copy-id between the system Zathras is installed on and the SUT.
****If working in a cloud environment do not perform the ssh-copy-id.
****Update/create the test configuration files in /zathras/config/ to reflect your requirements.
```

This PR predates the issue/JIRA ticket implementation.

2025-01-14 13:27 UTC, dvalinrh requested changes

2025-01-14 13:27 UTC, dvalinrh commented on bin/install.sh
> +echo "****If working in a cloud environment do not perform the ssh-copy-id."
Remove trailing spaces

2025-01-14 13:27 UTC, dvalinrh commented on bin/install.sh
Fix indentation and fix sudo sudo

2025-01-14 13:32 UTC, grdumas commented on bin/install.sh
Changes made, good catch.

2025-01-14 15:03 UTC, dvalinrh approved these changes

2025-01-14 21:09 UTC, merged