Fix selinux support.
redhat-performance/zathras pull request #82
Opened 2024-05-23 09:12 UTC by dvalinrh

Fix selinux so for Amazon and RHEL 2 ways to disable

First way is via the selinux config file (what we have been doing).
Second way is via grubby, to totally disable selinux.

Also add the ability to designated, enforcing,permissive and disabled.

For Ubuntu add code to install selinux on the OS.  Note at this time, enforcing is not supported.

2024-05-23 14:30 UTC, kdvalin requested changes

2024-05-23 14:30 UTC, kdvalin commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --remove-args=\"selinux\""
If we're enabling SELinux why are we removing it from ALL kernels?

2024-05-23 14:30 UTC, kdvalin commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --args=\"selinux=0\""
We should be only updating the running kernel, I think it's safe to assume most of us set the kernel we're using to the default via `grubby`

2024-05-23 21:57 UTC, dvalinrh commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --args=\"selinux=0\""
Default is for it not to be present.  If we do not do this, the cloud systems will come up with it disabled via the config file, but not the kernel.  Causes extra code path to be executed.

2024-05-28 12:53 UTC, dvalinrh commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --remove-args=\"selinux\""
By default selinix is 1.  If selinux is in the grubby line, it will be set to selinux=0, which disables it all the way.

2024-05-28 13:10 UTC, kdvalin commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --remove-args=\"selinux\""
Maybe something a bit clearer on the `name` then.  Something like "Remove selinux disable kernel arg" or something like that.

2024-05-29 15:21 UTC, dvalinrh commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --args=\"selinux=0\""
Fixed.

2024-05-29 15:24 UTC, dvalinrh commented on ansible_roles/roles/selinux_config/tasks/main.yml
> +      shell: "grubby --update-kernel=ALL --remove-args=\"selinux\""
Comment added.

2024-05-29 15:30 UTC, kdvalin approved these changes
LGTM

2024-05-29 15:33 UTC, merged